-- Supabase Schema for Film Production App

-- Create custom types
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'legal_doc_status') THEN
        CREATE TYPE public.legal_doc_status AS ENUM ('Signed', 'Pending');
    END IF;
END$$;


-- Create Tables

CREATE TABLE IF NOT EXISTS public.call_sheets (
    id bigint generated by default as identity primary key,
    project_id text not null,
    date date,
    call_time time,
    location text,
    director text,
    director_phone text,
    producer text,
    producer_phone text,
    created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.tasks (
    id bigint generated by default as identity primary key,
    project_id text not null,
    title text,
    completed boolean default false,
    created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.files (
    id bigint generated by default as identity primary key,
    project_id text not null,
    name text,
    size bigint,
    url text,
    created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.shot_list (
    id bigint generated by default as identity primary key,
    project_id text not null,
    scene integer,
    shot integer,
    description text,
    created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.legal_docs (
    id bigint generated by default as identity primary key,
    project_id text not null,
    name text,
    status public.legal_doc_status default 'Pending',
    url text,
    created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.budgets (
    id bigint generated by default as identity primary key,
    project_id text not null,
    total_budget numeric,
    spent numeric,
    created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.schedules (
    id bigint generated by default as identity primary key,
    project_id text not null,
    pre_production_start date,
    pre_production_end date,
    production_start date,
    production_end date,
    post_production_start date,
    post_production_end date,
    created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.team_members (
    id bigint generated by default as identity primary key,
    project_id text not null,
    name text,
    role text,
    created_at timestamp with time zone default now()
);

-- NEW: Table to explicitly link users to projects
CREATE TABLE IF NOT EXISTS public.project_members (
    id bigint generated by default as identity primary key,
    project_id text not null,
    user_id text not null,
    role text not null default 'member',
    created_at timestamp with time zone default now(),
    unique(project_id, user_id)
);

------------------------------------------------------------
-- NEW: Functions and Triggers for Clean Project Membership
------------------------------------------------------------

-- 1. This function adds the creator of a new project to the project_members table.
CREATE OR REPLACE FUNCTION public.handle_new_project_creator()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.project_members (project_id, user_id, role)
  VALUES (NEW.id, NEW.creator_id::text, 'creator');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. This trigger will automatically run the function above when a new project is created.
DROP TRIGGER IF EXISTS project_create_room_trigger ON public.projects;
DROP TRIGGER IF EXISTS on_new_project_add_creator ON public.projects;
CREATE TRIGGER on_new_project_add_creator
  AFTER INSERT ON public.projects
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_project_creator();

-- 3. We also drop the old function that was tied to the old trigger.
DROP FUNCTION IF EXISTS public.create_project_discussion_room();
