-- Run this SQL in your Supabase Dashboard SQL Editor to fix the 404 errors for skills and experience

-- Create user_skills table
CREATE TABLE IF NOT EXISTS public.user_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    skill_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(user_id, skill_name)
);

-- Enable RLS for user_skills
ALTER TABLE public.user_skills ENABLE ROW LEVEL SECURITY;

-- Create policies for user_skills
DROP POLICY IF EXISTS "Public skills are viewable by everyone" ON public.user_skills;
CREATE POLICY "Public skills are viewable by everyone" ON public.user_skills FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own skills" ON public.user_skills;
CREATE POLICY "Users can insert their own skills" ON public.user_skills FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own skills" ON public.user_skills;
CREATE POLICY "Users can delete their own skills" ON public.user_skills FOR DELETE USING (auth.uid() = user_id);


-- Create user_experience table
CREATE TABLE IF NOT EXISTS public.user_experience (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title text NOT NULL,
    company text NOT NULL,
    start_date date NOT NULL,
    end_date date,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS for user_experience
ALTER TABLE public.user_experience ENABLE ROW LEVEL SECURITY;

-- Create policies for user_experience
DROP POLICY IF EXISTS "Public experience is viewable by everyone" ON public.user_experience;
CREATE POLICY "Public experience is viewable by everyone" ON public.user_experience FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own experience" ON public.user_experience;
CREATE POLICY "Users can insert their own experience" ON public.user_experience FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own experience" ON public.user_experience;
CREATE POLICY "Users can update their own experience" ON public.user_experience FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own experience" ON public.user_experience;
CREATE POLICY "Users can delete their own experience" ON public.user_experience FOR DELETE USING (auth.uid() = user_id);
