-- 20250121000000_fresh_init.sql

-- 1. Extensions & Types
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DO $$ BEGIN
    CREATE TYPE public.project_space_type AS ENUM ('public', 'private', 'secret');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Profiles (Base User Data)
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    updated_at timestamp with time zone,
    username text UNIQUE,
    full_name text,
    avatar_url text,
    website text,
    bio text,
    location text,
    experience text,
    craft text,
    instagram_url text,
    youtube_url text,
    CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- 3. Project Spaces & Categories
CREATE TABLE IF NOT EXISTS public.project_space_categories (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name text NOT NULL UNIQUE,
    description text
);

CREATE TABLE IF NOT EXISTS public.project_spaces (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    description text,
    creator_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    category_id uuid REFERENCES public.project_space_categories(id) ON DELETE SET NULL,
    tags text[],
    last_activity_at timestamp with time zone DEFAULT now(),
    project_space_type public.project_space_type DEFAULT 'public'::project_space_type,
    -- Extended columns
    status TEXT, 
    location TEXT, 
    genre TEXT[], 
    required_roles TEXT[],
    budget_min NUMERIC, 
    budget_max NUMERIC, 
    start_date DATE, 
    end_date DATE
);

CREATE TABLE IF NOT EXISTS public.project_space_members (
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (project_space_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.project_space_join_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status text DEFAULT 'pending'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.project_space_bookmarks (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(user_id, project_space_id)
);

-- 4. Tasks (Project Management)
CREATE TABLE IF NOT EXISTS public.tasks (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    due_date date,
    assignee_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    is_completed boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- 5. Feed & Posts
CREATE TABLE IF NOT EXISTS public.posts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content text NOT NULL,
    media_url text,
    media_type text,
    tags text[],
    like_count integer DEFAULT 0,
    comment_count integer DEFAULT 0,
    share_count integer DEFAULT 0,
    has_ai_generated boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.likes (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.comments (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    parent_comment_id uuid REFERENCES public.comments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.shares (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (post_id, user_id)
);

-- 6. Discussion Rooms
CREATE TABLE IF NOT EXISTS public.room_categories (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.discussion_rooms (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    title text NOT NULL,
    name text NOT NULL, -- kept for compatibility
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    is_public boolean DEFAULT true,
    member_count integer DEFAULT 0,
    room_type text DEFAULT 'public',
    project_id uuid REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    creator_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    category_id uuid REFERENCES public.room_categories(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.room_members (
    room_id uuid NOT NULL REFERENCES public.discussion_rooms(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.room_messages (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    room_id uuid NOT NULL REFERENCES public.discussion_rooms(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    priority text DEFAULT 'normal',
    visibility_role text DEFAULT 'everyone'
);

CREATE TABLE IF NOT EXISTS public.room_join_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    room_id uuid NOT NULL REFERENCES public.discussion_rooms(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    status text DEFAULT 'pending'::text NOT NULL
);

-- 7. Direct Messaging (Conversations)
CREATE TABLE IF NOT EXISTS public.conversations (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    user1_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    user2_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    UNIQUE (user1_id, user2_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    conversation_id uuid NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    sender_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content text NOT NULL,
    is_read boolean DEFAULT false
);

-- 8. Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type text NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    action_url text,
    related_id uuid,
    related_type text,
    priority text DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
    is_read boolean DEFAULT false,
    is_actionable boolean DEFAULT false,
    metadata jsonb,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 9. Announcements
CREATE TABLE IF NOT EXISTS public.announcements (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    title text NOT NULL,
    content text NOT NULL,
    posted_at timestamp with time zone DEFAULT now() NOT NULL,
    author_id uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 10. User Details (Skills & Experience)
CREATE TABLE IF NOT EXISTS public.user_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    skill_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_experience (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title text NOT NULL,
    company text NOT NULL,
    start_date date NOT NULL,
    end_date date,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- ============================================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================================

-- Handle New User (Profile Creation)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, avatar_url)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'username', 
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Update Updated At
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_posts_updated_at ON public.posts;
CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON public.posts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_notifications_updated_at ON public.notifications;
CREATE TRIGGER update_notifications_updated_at BEFORE UPDATE ON public.notifications FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Update Room Member Count
CREATE OR REPLACE FUNCTION public.update_room_member_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE public.discussion_rooms SET member_count = member_count + 1 WHERE id = NEW.room_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE public.discussion_rooms SET member_count = GREATEST(0, member_count - 1) WHERE id = OLD.room_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_member_count_on_join ON public.room_members;
CREATE TRIGGER update_member_count_on_join AFTER INSERT ON public.room_members FOR EACH ROW EXECUTE FUNCTION public.update_room_member_count();

DROP TRIGGER IF EXISTS update_member_count_on_leave ON public.room_members;
CREATE TRIGGER update_member_count_on_leave AFTER DELETE ON public.room_members FOR EACH ROW EXECUTE FUNCTION public.update_room_member_count();

-- ============================================================================
-- RLS POLICIES (Permissive & Simple)
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_spaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_experience ENABLE ROW LEVEL SECURITY;

-- Profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Project Spaces
DROP POLICY IF EXISTS "Anyone can view project spaces" ON public.project_spaces;
CREATE POLICY "Anyone can view project spaces" ON public.project_spaces FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can create project spaces" ON public.project_spaces;
CREATE POLICY "Authenticated users can create project spaces" ON public.project_spaces FOR INSERT WITH CHECK (auth.uid() = creator_id);

DROP POLICY IF EXISTS "Creators can update their project spaces" ON public.project_spaces;
CREATE POLICY "Creators can update their project spaces" ON public.project_spaces FOR UPDATE USING (auth.uid() = creator_id);

DROP POLICY IF EXISTS "Creators can delete their project spaces" ON public.project_spaces;
CREATE POLICY "Creators can delete their project spaces" ON public.project_spaces FOR DELETE USING (auth.uid() = creator_id);

-- Project Space Members
DROP POLICY IF EXISTS "Anyone can view project members" ON public.project_space_members;
CREATE POLICY "Anyone can view project members" ON public.project_space_members FOR SELECT USING (true);

DROP POLICY IF EXISTS "Creators can manage members" ON public.project_space_members;
CREATE POLICY "Creators can manage members" ON public.project_space_members FOR ALL USING (
    EXISTS (SELECT 1 FROM public.project_spaces WHERE id = project_space_id AND creator_id = auth.uid())
);

DROP POLICY IF EXISTS "Users can join/leave" ON public.project_space_members;
CREATE POLICY "Users can join/leave" ON public.project_space_members FOR ALL USING (user_id = auth.uid());

-- Project Categories
DROP POLICY IF EXISTS "Anyone can view categories" ON public.project_space_categories;
CREATE POLICY "Anyone can view categories" ON public.project_space_categories FOR SELECT USING (true);

-- Bookmarks
DROP POLICY IF EXISTS "Users can manage their own bookmarks" ON public.project_space_bookmarks;
CREATE POLICY "Users can manage their own bookmarks" ON public.project_space_bookmarks FOR ALL USING (auth.uid() = user_id);

-- Posts
DROP POLICY IF EXISTS "Anyone can view posts" ON public.posts;
CREATE POLICY "Anyone can view posts" ON public.posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can create posts" ON public.posts;
CREATE POLICY "Authenticated users can create posts" ON public.posts FOR INSERT WITH CHECK (auth.uid() = author_id);

DROP POLICY IF EXISTS "Authors can update/delete their posts" ON public.posts;
CREATE POLICY "Authors can update/delete their posts" ON public.posts FOR ALL USING (auth.uid() = author_id);

-- Discussion Rooms
DROP POLICY IF EXISTS "Anyone can view public rooms" ON public.discussion_rooms;
CREATE POLICY "Anyone can view public rooms" ON public.discussion_rooms FOR SELECT USING (is_public = true OR auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated users can create rooms" ON public.discussion_rooms;
CREATE POLICY "Authenticated users can create rooms" ON public.discussion_rooms FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Creators can update/delete rooms" ON public.discussion_rooms;
CREATE POLICY "Creators can update/delete rooms" ON public.discussion_rooms FOR ALL USING (creator_id = auth.uid());

-- Room Messages
DROP POLICY IF EXISTS "Anyone can view messages" ON public.room_messages;
CREATE POLICY "Anyone can view messages" ON public.room_messages FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can send messages" ON public.room_messages;
CREATE POLICY "Authenticated users can send messages" ON public.room_messages FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own messages" ON public.room_messages;
CREATE POLICY "Users can delete their own messages" ON public.room_messages FOR DELETE USING (auth.uid() = user_id);

-- Room Join Requests
DROP POLICY IF EXISTS "Users can create join requests" ON public.room_join_requests;
CREATE POLICY "Users can create join requests" ON public.room_join_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Room creators can view join requests" ON public.room_join_requests;
CREATE POLICY "Room creators can view join requests" ON public.room_join_requests FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.discussion_rooms WHERE id = room_id AND creator_id = auth.uid())
);

DROP POLICY IF EXISTS "Room creators can manage join requests" ON public.room_join_requests;
CREATE POLICY "Room creators can manage join requests" ON public.room_join_requests FOR ALL USING (
    EXISTS (SELECT 1 FROM public.discussion_rooms WHERE id = room_id AND creator_id = auth.uid())
);

-- Notifications
DROP POLICY IF EXISTS "Users can view/manage their own notifications" ON public.notifications;
CREATE POLICY "Users can view/manage their own notifications" ON public.notifications FOR ALL USING (auth.uid() = user_id);

-- Announcements
DROP POLICY IF EXISTS "Anyone can view announcements" ON public.announcements;
CREATE POLICY "Anyone can view announcements" ON public.announcements FOR SELECT USING (true);

-- General fallback for other tables (Likes, Comments, etc.)
DROP POLICY IF EXISTS "Public view likes" ON public.likes;
CREATE POLICY "Public view likes" ON public.likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "User manage likes" ON public.likes;
CREATE POLICY "User manage likes" ON public.likes FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Public view comments" ON public.comments;
CREATE POLICY "Public view comments" ON public.comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "User manage comments" ON public.comments;
CREATE POLICY "User manage comments" ON public.comments FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Public view shares" ON public.shares;
CREATE POLICY "Public view shares" ON public.shares FOR SELECT USING (true);

DROP POLICY IF EXISTS "User manage shares" ON public.shares;
CREATE POLICY "User manage shares" ON public.shares FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "User manage conversations" ON public.conversations;
CREATE POLICY "User manage conversations" ON public.conversations FOR ALL USING (auth.uid() = user1_id OR auth.uid() = user2_id);

DROP POLICY IF EXISTS "User manage messages" ON public.messages;
CREATE POLICY "User manage messages" ON public.messages FOR ALL USING (auth.uid() = sender_id OR conversation_id IN (SELECT id FROM public.conversations WHERE user1_id = auth.uid() OR user2_id = auth.uid()));

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_spaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_skills ENABLE ROW LEVEL SECURITY;

-- Permissive policies for development (allow all authenticated users)
CREATE POLICY "Allow all for authenticated users" ON public.profiles FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.project_spaces FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.project_space_members FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.project_space_join_requests FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.project_space_bookmarks FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.tasks FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.posts FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.comments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.likes FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.shares FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.discussion_rooms FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.room_members FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.room_messages FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.room_join_requests FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.conversations FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.messages FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.notifications FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.announcements FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated users" ON public.user_skills FOR ALL USING (auth.role() = 'authenticated');

-- ============================================================================
-- DATA SEEDING
-- ============================================================================

INSERT INTO public.project_space_categories (name, description) VALUES 
('Film', 'Feature films, short films, and documentaries'),
('TV', 'Television series and pilots'),
('Commercial', 'Commercials and advertising'),
('Music Video', 'Music videos'),
('Web Series', 'Web series and online content')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.room_categories (name) VALUES 
('General'),
('Cinematography'),
('Directing'),
('Production'),
('Post-Production'),
('Screenwriting'),
('Sound Design'),
('Visual Effects')
ON CONFLICT (name) DO NOTHING;
